In [61]:
import pandas as pd
import numpy as np

In [62]:
df = pd.read_csv('../data/listings2025-03.csv')
print(df.head())

      id                         listing_url       scrape_id last_scraped  \
0  75212  https://www.airbnb.com/rooms/75212  20250301213405   2025-03-03
1  76561  https://www.airbnb.com/rooms/76561  20250301213405   2025-03-03
2  79502  https://www.airbnb.com/rooms/79502  20250301213405   2025-03-03
3  79832  https://www.airbnb.com/rooms/79832  20250301213405   2025-03-02
4  80714  https://www.airbnb.com/rooms/80714  20250301213405   2025-03-03

        source                                              name  \
0  city scrape      Sunny Room only in town house nr Long Beachâ€¦
1  city scrape  420 Friendly Sweet Lil' Guesthouse by Sofi & LAX
2  city scrape     Silver Lake  million dollar view * luxe patio
3  city scrape               Guest Quarters @ the Hollywood Sign
4  city scrape                Cozy secluded Guesthouse in Garden

                                         description  \
0  A bright & sunny room ONLY with full size bed,...
1  -420 Friendly Airbnb Stay in LA!-<br />(16 to ...
2  Walk to Sunset Junction, the Polka Dot triangl...
3                                        Guest House
4  Sierra Bonita Guesthouse in Garden setting:<br...

                               neighborhood_overview  \
0  A really lovely area, with so many restaurants...
1  Q: WHAT'S THE NEIGHBORHOOD LIKE?<br /><br />A:...
2  We have the absolute  iconic views of downtown...
3                                                NaN
4  We are very central to so many tourist destina...

                                         picture_url  host_id  ...  \
0  https://a0.muscache.com/pictures/e3cff12f-d518...   343761  ...
1  https://a0.muscache.com/pictures/23627d22-d977...   403838  ...
2  https://a0.muscache.com/pictures/miso/Hosting-...   428171  ...
3  https://a0.muscache.com/pictures/541078/35c6dc...    28569  ...
4  https://a0.muscache.com/pictures/2080263/2d8a6...   436647  ...

  review_scores_communication review_scores_location review_scores_value  \
0                        4.96                   4.89                4.83
1                        4.94                   4.70                4.79
2                        4.88                   4.94                4.73
3                        4.95                   4.93                4.91
4                        4.98                   4.95                4.88

        license instant_bookable calculated_host_listings_count  \
0           NaN                f                              1
1           NaN                f                              4
2           NaN                f                              2
3  HSR19-002716                f                              1
4  HSR19-003488                f                              1

  calculated_host_listings_count_entire_homes  \
0                                           0
1                                           4
2                                           2
3                                           1
4                                           1

  calculated_host_listings_count_private_rooms  \
0                                            1
1                                            0
2                                            0
3                                            0
4                                            0

  calculated_host_listings_count_shared_rooms reviews_per_month
0                                           0              0.46
1                                           0              5.30
2                                           0              1.78
3                                           0              2.84
4                                           0              1.16

[5 rows x 79 columns]

In [63]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45031 entries, 0 to 45030
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            45031 non-null  int64
 1   listing_url                                   45031 non-null  object
 2   scrape_id                                     45031 non-null  int64
 3   last_scraped                                  45031 non-null  object
 4   source                                        45031 non-null  object
 5   name                                          45030 non-null  object
 6   description                                   43998 non-null  object
 7   neighborhood_overview                         21333 non-null  object
 8   picture_url                                   45031 non-null  object
 9   host_id                                       45031 non-null  int64
 10  host_url                                      45031 non-null  object
 11  host_name                                     44961 non-null  object
 12  host_since                                    44958 non-null  object
 13  host_location                                 34474 non-null  object
 14  host_about                                    24524 non-null  object
 15  host_response_time                            34627 non-null  object
 16  host_response_rate                            34627 non-null  object
 17  host_acceptance_rate                          35297 non-null  object
 18  host_is_superhost                             43513 non-null  object
 19  host_thumbnail_url                            44958 non-null  object
 20  host_picture_url                              44958 non-null  object
 21  host_neighbourhood                            35397 non-null  object
 22  host_listings_count                           44958 non-null  float64
 23  host_total_listings_count                     44958 non-null  float64
 24  host_verifications                            44958 non-null  object
 25  host_has_profile_pic                          44958 non-null  object
 26  host_identity_verified                        44958 non-null  object
 27  neighbourhood                                 21334 non-null  object
 28  neighbourhood_cleansed                        45031 non-null  object
 29  neighbourhood_group_cleansed                  45031 non-null  object
 30  latitude                                      45031 non-null  float64
 31  longitude                                     45031 non-null  float64
 32  property_type                                 45031 non-null  object
 33  room_type                                     45031 non-null  object
 34  accommodates                                  45031 non-null  int64
 35  bathrooms                                     35923 non-null  float64
 36  bathrooms_text                                45003 non-null  object
 37  bedrooms                                      42037 non-null  float64
 38  beds                                          35808 non-null  float64
 39  amenities                                     45031 non-null  object
 40  price                                         35867 non-null  object
 41  minimum_nights                                45031 non-null  int64
 42  maximum_nights                                45031 non-null  int64
 43  minimum_minimum_nights                        45011 non-null  float64
 44  maximum_minimum_nights                        45011 non-null  float64
 45  minimum_maximum_nights                        45011 non-null  float64
 46  maximum_maximum_nights                        45011 non-null  float64
 47  minimum_nights_avg_ntm                        45011 non-null  float64
 48  maximum_nights_avg_ntm                        45011 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              41665 non-null  object
 51  availability_30                               45031 non-null  int64
 52  availability_60                               45031 non-null  int64
 53  availability_90                               45031 non-null  int64
 54  availability_365                              45031 non-null  int64
 55  calendar_last_scraped                         45031 non-null  object
 56  number_of_reviews                             45031 non-null  int64
 57  number_of_reviews_ltm                         45031 non-null  int64
 58  number_of_reviews_l30d                        45031 non-null  int64
 59  availability_eoy                              45031 non-null  int64
 60  number_of_reviews_ly                          45031 non-null  int64
 61  estimated_occupancy_l365d                     45031 non-null  int64
 62  estimated_revenue_l365d                       35867 non-null  float64
 63  first_review                                  32383 non-null  object
 64  last_review                                   32383 non-null  object
 65  review_scores_rating                          32383 non-null  float64
 66  review_scores_accuracy                        32375 non-null  float64
 67  review_scores_cleanliness                     32375 non-null  float64
 68  review_scores_checkin                         32367 non-null  float64
 69  review_scores_communication                   32373 non-null  float64
 70  review_scores_location                        32366 non-null  float64
 71  review_scores_value                           32365 non-null  float64
 72  license                                       12735 non-null  object
 73  instant_bookable                              45031 non-null  object
 74  calculated_host_listings_count                45031 non-null  int64
 75  calculated_host_listings_count_entire_homes   45031 non-null  int64
 76  calculated_host_listings_count_private_rooms  45031 non-null  int64
 77  calculated_host_listings_count_shared_rooms   45031 non-null  int64
 78  reviews_per_month                             32383 non-null  float64
dtypes: float64(23), int64(20), object(36)
memory usage: 27.1+ MB

In [65]:
df.describe()

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,4.503100e+04,4.503100e+04,4.503100e+04,44958.000000,44958.000000,45031.000000,45031.000000,45031.000000,35923.000000,42037.000000,...,32375.000000,32367.000000,32373.000000,32366.000000,32365.000000,45031.000000,45031.000000,45031.000000,45031.000000,32383.000000
mean,6.015591e+17,2.025030e+13,2.049582e+08,112.416389,147.666889,34.055353,-118.309365,4.057960,1.654497,1.802127,...,4.754504,4.863075,4.862665,4.797147,4.712069,19.402878,16.118541,2.609758,0.074327,1.353439
std,5.435503e+17,0.000000e+00,2.019698e+08,664.725939,795.518788,0.144720,0.172918,2.887477,1.235461,1.337568,...,0.429615,0.352581,0.365785,0.378640,0.441847,68.991570,67.930701,10.284036,0.954346,1.699283
min,2.708000e+03,2.025030e+13,7.670000e+02,0.000000,0.000000,33.338540,-118.917134,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.010000
25%,3.559098e+07,2.025030e+13,2.748408e+07,1.000000,2.000000,33.997750,-118.410305,2.000000,1.000000,1.000000,...,4.690000,4.870000,4.880000,4.750000,4.660000,1.000000,1.000000,0.000000,0.000000,0.200000
50%,7.199223e+17,2.025030e+13,1.196765e+08,3.000000,5.000000,34.061390,-118.340614,3.000000,1.000000,1.000000,...,4.880000,4.970000,4.980000,4.910000,4.820000,2.000000,1.000000,0.000000,0.000000,0.700000
75%,1.131384e+18,2.025030e+13,3.837909e+08,13.000000,19.000000,34.108296,-118.221685,6.000000,2.000000,2.000000,...,5.000000,5.000000,5.000000,5.000000,4.960000,10.000000,5.000000,1.000000,0.000000,2.020000
max,1.366924e+18,2.025030e+13,6.815765e+08,5255.000000,9055.000000,34.811180,-117.653350,16.000000,47.500000,43.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,582.000000,582.000000,100.000000,19.000000,68.520000

In [66]:
for col in df.select_dtypes(include=['object']).columns:
    print(f"Unique values in '{col}':")
    print(df[col].unique())
    print('-'*40)

Unique values in 'listing_url':
['https://www.airbnb.com/rooms/75212' 'https://www.airbnb.com/rooms/76561'
 'https://www.airbnb.com/rooms/79502' ...
 'https://www.airbnb.com/rooms/1366915876833701496'
 'https://www.airbnb.com/rooms/1366922337013976727'
 'https://www.airbnb.com/rooms/1366923674056931351']
----------------------------------------
Unique values in 'last_scraped':
['2025-03-03' '2025-03-02']
----------------------------------------
Unique values in 'source':
['city scrape' 'previous scrape']
----------------------------------------
Unique values in 'name':
['Sunny Room only in town house nr Long Beachâ€¦'
 "420 Friendly Sweet Lil' Guesthouse by Sofi & LAX"
 'Silver Lake  million dollar view * luxe patio' ...
 'Luxury 3BR Home with Private Jacuzzi and Parking'
 'Small Sailboat hideaway'
 'Unit A Great 1 bedroom 2 baths in Beverly Hills']
----------------------------------------
Unique values in 'description':
['A bright & sunny room ONLY with full size bed, tv and wifi in town house. We have an outside patio where you can enjoy a glass of wine and watch the hummingbirds. 2 mins from freeway.<br />Note: Not suitable for children under 12, no animals ( due to allergies) no discounts.<br />Full profile, pic and read full listing and rules before making a request. After reservation has been made, we require a copy of ID, for verification purposes.'
 '-420 Friendly Airbnb Stay in LA!-<br />(16 to 24 Miles away from the Wildfires. Far from danger zones)<br />4 miles to Sofi Stadium<br />5 miles to USC<br />6 miles to LAX<br />8 miles to Hollywood<br />8 miles to Downtown Los Angeles<br /><br />400 sq ft Single Room Guest Suite with high ceilings, free driveway parking & a lovely park only steps away.<br />Sleeps 4 - 3 Beds - 1 Queen Size & 2 Twin Trundle Beds - 1 Bathroom<br />-Note - This is a SINGLE LARGE ROOM--No Seperate Bedrooms -<br />Free Parking - Roku + Wifi + 24Hr Check In.'
 'Walk to Sunset Junction, the Polka Dot triangle, Virgil Village & Farmers markets but sleep without the noise of Sunset.  Perched high on the hill, bask in our classic downtown skyline all the way to Long Beach. Your private modern apartment shares the property and patio w/larger home in a quiet residential area. Enjoy our lush garden with fruit trees and oversized patio. Easy street parking, free laundry & great wifi await you.'
 ...
 'The whole group will enjoy easy access to everything from this centrally located place.Bold and extraordinary, this inspired custom home enters the fray in the beating heart of Silver Lake.<br /><br /> A massive pivoting solid oak door greets you as you step onto the full-bodied white oak floors surrounded by towering gallery walls with natural light flooding the space through the oversized Fleetwood Windows. Every detail of this house is custom with an inspired vision - no expense was spared.'
 "Welcome to this stunning 3-bedroom, 3-bathroom home, designed for both comfort and style, offering a modern and spacious ambiance in one of the city's most sought-after neighborhoods. Nestled in a safe and quiet area of Westwood, this property is ideal for families, business travelers, and groups looking for a high-end stay with top-notch amenities."
 'Stay in a peaceful, centrally located spot in the heart of Beverly Hills! Just a 5-minute walk to Rodeo Drive and top attractions. This cozy 1-bedroom, 2-bath apartment features a spacious living and dining area, plus all essentials like hot water, AC, and a Roku TV. Washer and dryer available in the garage, with free parking in the back. Need extra parking? We can provide a street pass for overnight stays. Perfect for a comfortable and convenient stay!']
----------------------------------------
Unique values in 'neighborhood_overview':
['A really lovely area, with so many restaurants within walking distance. Huge mall really close by. 2 mins from the freeways to get anywhere in California <br /><br />Parking on the main road, if no spaces available in the complex. We are not liable for any tickets and breakins to the car. Street cleaning on Tuesdays, please make sure car is not parked on the main road on that day'
 'Q: WHAT\'S THE NEIGHBORHOOD LIKE?<br /><br />A: View Park - Windsor Hills (from Wikipedia)<br />The two neighborhoods are part of a band of neighborhoods, from Culver City\'s Fox Hills district on the west to the Los Angeles neighborhood of Leimert Park on the east, that compose the single largest and one of the wealthiest geographically contiguous high upper-class communities for people of color in the western United States. This corridor also includes Baldwin Hills and Ladera Heights neighborhoods. "Wikipedia"<br /><br />It\'s very safe, with friendly people & super convenient to get to most of LA quickly. We have tons of lovely parks around. We even have one right across the street. And did I mention LAX Airport is only 15 minutes away? <br /><br />If you go down the street we have a huge Westfield Plaza with a TARGET and many stores for all of your shopping needs. As well as a SPROUTS organic market, across the street from the mall. Visit the Newest TRADER JOES location next to the We'
 'We have the absolute  iconic views of downtown Los Angeles.  Our private apartment is clean and minimal. We live in the property and take the utmost care of our place so that our guests have the best possible experience.'
 ...
 'Location! Location! Location and Perfect Home Base for a group. This property is right off Melrose Ave, one of the most well-known and exciting streets in Los Angeles! Past Guests have loved being such a short walk from so many restaurants, cafes, and stores. Many other attractions such as the Grove, Hollywood, and Universal Studios are just a short drive away.'
 'Situated in the Rampart Village neighborhood, a vibrant and diverse community in Central Los Angeles.<br /><br />Walkability and Transportation: This location boasts a high Walk Score of 84, indicating that most daily errands can be accomplished on foot. Public transportation is readily accessible, with the Metro B Line (Red) Vermont/Beverly Station approximately a 10-minute walk away. <br /><br />Additionally, several bus lines serve the area, providing convenient options for commuting and exploring the city. <br /><br /><br />Proximity to Notable Areas: Rampart Village is centrally located, offering easy access to several notable Los Angeles neighborhoods:<br /><br />Historic Filipinotown: Located just to the south, this area celebrates Filipino-American culture and history, featuring various cultural landmarks and eateries. <br /><br />Little Armenia: Situated to the northwest, this neighborhood is rich in Armenian culture, with numerous restaurants, shops, and cultural centers. <br'
 'Perfect location near all for the beach and Beverly Hills and around']
----------------------------------------
Unique values in 'picture_url':
['https://a0.muscache.com/pictures/e3cff12f-d518-43e3-af33-1f5e7fb200a5.jpg'
 'https://a0.muscache.com/pictures/23627d22-d977-4282-8301-7f865a3e2217.jpg'
 'https://a0.muscache.com/pictures/miso/Hosting-79502/original/a19372c9-e38b-459f-ac59-7ef0e46920d1.jpeg'
 ...
 'https://a0.muscache.com/pictures/miso/Hosting-1366915876833701496/original/ff2b0299-f294-484f-9757-bf31089466fa.jpeg'
 'https://a0.muscache.com/pictures/hosting/Hosting-1366922337013976727/original/ade2ac7b-42fc-4d0b-9f23-f75483ee5484.jpeg'
 'https://a0.muscache.com/pictures/miso/Hosting-1366923674056931351/original/719b9b07-ac0c-43c5-9128-fc710a9726de.jpeg']
----------------------------------------
Unique values in 'host_url':
['https://www.airbnb.com/users/show/343761'
 'https://www.airbnb.com/users/show/403838'
 'https://www.airbnb.com/users/show/428171' ...
 'https://www.airbnb.com/users/show/594000182'
 'https://www.airbnb.com/users/show/681576491'
 'https://www.airbnb.com/users/show/237273850']
----------------------------------------
Unique values in 'host_name':
['Kris' 'Jennifer' 'H.' ... 'Anjana' 'Gabbie' 'Angelique M']
----------------------------------------
Unique values in 'host_since':
['2011-01-11' '2011-02-22' '2011-03-07' ... '2025-02-25' '2025-02-26'
 '2025-02-28']
----------------------------------------
Unique values in 'host_location':
['Lakewood, CA' 'Los Angeles, CA' 'Lynwood, CA' nan 'Long Beach, CA'
 'Agoura Hills, CA' 'Santa Monica, CA' 'Bellflower, CA'
 'California, United States' 'Beverly Hills, CA' 'New York, NY'
 'West Hollywood, CA' 'Redondo Beach, CA' 'United States'
 'Santa Clarita, CA' 'Las Vegas, NV' 'Culver City, CA' 'Malibu, CA'
 'Newport Beach, CA' 'Carson, CA' 'Camarillo, CA' 'Venice, CA'
 'Hermosa Beach, CA' 'Marina Del Rey, CA' 'Palm Springs, CA'
 'Topanga Canyon, CA' 'Durham, NC' 'Pasadena, CA'
 'Puerto Escondido, Mexico' 'Calabasas, CA' 'Topanga, CA'
 'North Hollywood, CA' 'Seattle, WA' 'Fort Lauderdale, FL' 'Hollywood, SC'
 'Calgary, Canada' 'South Pasadena, CA' 'Rancho Palos Verdes, CA'
 'Marina del Rey, CA' 'Manhattan Beach, CA' 'Ibarra, Ecuador'
 'Portland, OR' 'England, United Kingdom' 'Palos Verdes Peninsula, CA'
 'WINNETKA, CA' 'Monrovia, CA' 'San Francisco, CA' 'Whittier, CA'
 'Miami, FL' 'Los Angeles' 'Palm Desert, CA' 'Sliema, Malta' 'Denver, CO'
 'Louisville, KY' 'Lomita, CA' 'Altadena, CA' 'Santa Barbara, CA'
 'Decatur, GA' 'Tacoma, WA' 'Hawthorne, CA' 'Burbank, CA' 'Washington, DC'
 'El Segundo, CA' 'San Fernando, CA' 'Bozeman, MT' 'Bellevue, WA'
 'Mexico City, Mexico' 'West Covina, CA' 'Austin, TX' 'San Diego, CA'
 'Hingham, MA' 'Mission Viejo, CA' 'San Antonio, TX' 'Stockholm, Sweden'
 'Monte Nido, CA' 'GÃ¤vle, Sweden' 'San Gabriel, CA' 'Verona, Italy'
 'Walnut Creek, CA' 'Greenwich, CT' 'Santa Fe, NM' 'Torrance, CA'
 'Lawndale, CA' 'San Miguel de Allende, Mexico' 'Toronto, Canada'
 'Downey, CA' 'Boca Raton, FL' 'Glendale, CA' 'Miami Beach, FL'
 'Paros, Greece' 'Paris, France' 'Monterey Park, CA' 'Yakima, WA'
 'Bolsena, Italy' 'Bellingham, WA' 'Inglewood, CA' 'Chicago, IL'
 'Commerce City, CO' 'Claremont, CA' 'Rome, Italy' 'Sacramento, CA'
 'Montreal, Canada' 'San Francisco, Mexico' 'Arcadia, CA'
 'South Jordan, UT' 'Rathdrum, ID' 'Los Alamitos, CA' 'Val Verde, CA'
 'Rancho Mirage, CA' 'St. Petersburg, FL' 'San Jose, CA' 'Lafayette, CA'
 'Hacienda Heights, CA' 'Palos Verdes Estates, CA' 'Littlerock, CA'
 'Stateline, NV' 'La Crescenta-Montrose, CA' 'Compton, CA'
 'Antigua Guatemala, Guatemala' 'Corona, CA' 'Fort Worth, TX'
 'Garden Grove, CA' 'Homeland, CA' 'Anaheim, CA' 'Temple City, CA'
 'Irvine, CA' 'Temecula, CA' 'London, United Kingdom' 'Coronado, CA'
 'Palo Alto, CA' 'Lancaster, CA' 'La CaÃ±ada Flintridge, CA'
 'Bass Lake, CA' 'Chula Vista, CA' 'Yorba Linda, CA' 'Sunnyvale, CA'
 'Maine, United States' 'Alhambra, CA' 'Ojai, CA' 'Rowland Heights, CA'
 'La Habra, CA' 'Moss Beach, CA' 'Naperville, IL' 'Cerritos, CA'
 'Gardena, CA' 'Tucson, AZ' 'Pomona, CA' 'Nashville, TN'
 'British Columbia, Canada' 'Tiburon, CA' 'Huntington Beach, CA'
 'Lisbon, Portugal' 'Laos' 'Napa, CA' 'Halifax, Canada'
 'Portola Valley, CA' 'Avalon, CA' 'California' 'Hawaii, United States'
 'Arlington, VA' 'Azusa, CA' 'Dallas, TX' 'Walnut, CA'
 'Copenhagen, Denmark' 'Oklahoma City, OK' 'Skokie, IL' 'La Puente, CA'
 'Wrightwood, CA' 'Wilsall, MT' 'Orlando, FL' 'Glendora, CA' 'Boise, ID'
 'Coquitlam, Canada' 'Shingle Springs, CA' 'Washington, United States'
 'Melbourne, Australia' 'Belpre, OH' 'KonÃ¡rovice, Czechia'
 'Winchester, CA' 'Kaohsiung City, Taiwan' 'Pinole, CA' 'Berlin, Germany'
 'Murrieta, CA' 'Cambria, CA' 'Prague, Czechia' 'Nelson, Canada'
 'San Dimas, CA' 'Amsterdam, Netherlands' 'Notre Dame, IN'
 'Sebastopol, CA' 'Carlsbad, CA' 'Lake Forest, CA' 'Makawao, HI'
 'Rolling Hills Estates, CA' 'Houston, TX' 'Covina, CA' 'Dana Point, CA'
 'Bali, Indonesia' 'Sierra Madre, CA' 'Saint Peter Port, Guernsey'
 'Brittany, France' 'Bloomfield Hills, MI' 'Maroochydore, Australia'
 'Palmdale, CA' 'Philadelphia, PA' 'Diamond Bar, CA' 'Thousand Oaks, CA'
 'Italy' 'San Marino' 'Ventura, CA' 'Madison, WI' 'St Louis, MO'
 'Harker Heights, TX' 'Chandler, AZ' 'Boston, MA' 'Nice, France'
 'Asheville, NC' 'DÃ¼sseldorf, Germany' 'Fullerton, CA' 'Vancouver, Canada'
 'Acton, CA' 'Oakland, CA' 'Eugene, OR' 'Lindenwold, NJ' 'Palmyra, IN'
 'Tampa, FL' 'Joshua Tree, CA' 'Scottsdale, AZ' 'Aliso Viejo, CA'
 'Amalapuram, India' 'Hamburg, Germany' 'St. George, UT'
 'New South Wales, Australia' 'Bangalow, Australia' 'East Point, GA'
 'Stevenson Ranch, CA' 'Pico Rivera, CA' 'Del Monte Forest, CA'
 'Fort Collins, CO' 'Rapid City, SD' 'ZÃ¼rich, Switzerland'
 'White Plains, NY' 'Placentia, CA' 'Valyermo, CA' 'Colorado Springs, CO'
 'Sterling Heights, MI' 'Danville, CA' 'La Crosse, WI' 'Castaic, CA'
 'Hackensack, NJ' 'Northampton, MA' 'Tweed Heads, Australia'
 'Rosemead, CA' 'Duarte, CA' 'Mountain View, CA' 'Agua Dulce, CA'
 'Jackson, MS' 'Fort Washington, MD' 'Dothan, AL' 'Rio de Janeiro, Brazil'
 'Mill Valley, CA' 'Sayulita, Mexico' 'Signal Hill, CA'
 'Juniper Hills, CA' 'Lompoc, CA' 'Maple Grove, MN' 'Jersey City, NJ'
 'Minneapolis, MN' 'Granada, Spain' 'El Monte, CA' 'Norwalk, CA'
 'Fair Oaks, CA' 'Brampton, Canada' 'Daly City, CA' 'Massapequa Park, NY'
 'Bardstown, KY' 'Stockton, CA' 'Oregon, United States' 'Windsor, Canada'
 'Cary, NC' 'New Orleans, LA' 'Berkeley, CA' 'Springfield, CA' 'Taos, NM'
 'View Park-Windsor Hills, CA' 'Sydney, Australia' 'Riverside, CA'
 'Omaha, NE' 'Occidental, CA' 'Quartz Hill, CA' 'New York, United States'
 'San Bernardino, CA' 'Yerevan, Armenia' 'Nevada City, CA' 'Madrid, Spain'
 'Cleveland, OH' 'Toledo, OH' 'Del Aire, CA' 'California City, CA'
 'San Mateo, CA' 'Darby, PA' 'Cachagua, Chile' 'BogotÃ¡, Colombia'
 'Santa Fe Springs, CA' 'Fresno, CA' 'Katy, TX' 'Mendocino, CA'
 'Elk Grove, CA' 'Hollywood, FL' 'New Jersey, United States' 'Bangladesh'
 'City Terrace, CA' 'Hidden Hills, CA' 'Flower Mound, TX'
 'Pioneertown, CA' 'Del Rey, CA' 'Norco, CA' 'Bunker Hill, CA' 'Bend, OR'
 'West Rancho Dominguez, CA' 'Stuart, FL' 'Soquel, CA'
 'Dripping Springs, TX' 'Laguna Beach, CA' 'Brentwood, CA'
 'Charlestown, RI' 'Ann Arbor, MI' 'Monterey, CA' 'Happy Valley, OR'
 'Westlake Village, CA' 'Norman, OK' 'San Luis Obispo, CA' 'Accord, NY'
 'Detroit, MI' 'South Lake Tahoe, CA' 'La Verne, CA' 'Orange, CA'
 'Rockville, MD' 'Fairfield, CA' 'Huntington Park, CA' 'Franklin, MA'
 'Windermere, FL' 'Atlanta, GA' 'Santa Cruz, CA' 'Oranjestad, Aruba'
 'Calumet, OK' 'Baldwin Park, CA' 'China' 'Edmonton, Canada'
 'Antelope, CA' 'Tokyo, Japan' 'Puerto Rico' 'Oaxaca, Mexico'
 'Westwood, CA' 'Sleepy Hollow, NY' 'Longview, WA'
 'Seongnam-si, South Korea' 'Vail, CO' 'San Clemente, CA' 'Charlotte, NC'
 'Brevard, NC' 'Markham, Canada' 'Turin, Italy' 'Cambridge, MA'
 'Phoenix, AZ' 'Bron, France' 'Palos Heights, IL' 'Norridge, IL'
 'Truckee, CA' 'Portland, ME' 'Memphis, TN' 'Cottesloe, Australia'
 'Mammoth Lakes, CA' 'Tarragona, Spain' 'Hong Kong' 'Bentonville, AR'
 'Oceanside, CA' 'Bakersfield, CA' 'Easton, PA' 'Beachwood, OH'
 'Las Vegas, NM' 'Agde, France' 'Boulder, CO' 'Beijing, China'
 'Riyadh, Saudi Arabia' 'Rancho Cucamonga, CA'
 'Pennsylvania, United States' 'San Carlos, CA'
 'CastellÃ³n de la Plana, Spain' 'Royal Oak, MI' 'Henderson, NV'
 'Morristown, NJ' 'Seal Beach, CA' 'Venice, Italy' 'Niceville, FL'
 'Santa Ana, CA' 'Newark, CA' 'Honolulu, HI' 'East Los Angeles, CA'
 'Thailand' 'Lithonia, GA' 'Daytona Beach, FL' 'Montebello, CA'
 'Dubai, United Arab Emirates' 'Stillwater, NY' 'Bell, CA'
 'Istanbul, Turkey' 'Plano, TX' 'Rochester, NY'
 'Nueva Italia de Ruiz, Mexico' 'Cathedral City, CA' 'Allentown, PA'
 'Merced, CA' 'San Juan Capistrano, CA' 'Pawlet, VT' 'Paramount, CA'
 'Hewlett, NY' 'Montclair, NJ' 'San Juan, Puerto Rico' 'New Hope, PA'
 'Red Hill, Australia' 'Green Valley, CA' 'Birmingham, MI'
 'Steamboat Springs, CO' 'Ahmedabad, India' 'Simi Valley, CA'
 'Del Sur, CA' 'Anchorage, AK' 'Fontana, CA' 'Puebla, Mexico'
 'Haiku-Pauwela, HI' 'Florham Park, NJ' 'Fountain Valley, CA'
 'Calamvale, Australia' 'South Gate, CA' 'Crestline, CA' 'Morro Bay, CA'
 'Santa Clara, CA' 'City of Industry, CA' 'Hawaiian Gardens, CA'
 'Chino, CA' 'Brea, CA' 'Ontario, CA' 'Moscow, Russia' 'Hamar, Norway'
 'San Pablo, CA' 'Samara, Russia' 'Milan, Italy' 'South Africa'
 'New Taipei City, Taiwan' 'Worcester, MA' 'Fort Wayne, IN'
 'Tel Aviv-Yafo, Israel' 'Laguna Hills, CA' 'Wuhan, China' 'Stanton, CA'
 'Texas, United States' 'Big Bear Lake, CA' 'Háº£i ChÃ¢u District, Vietnam'
 'Kagel Canyon, CA' 'Kansas City, MO' 'Los Altos, CA' 'Perris, CA'
 'Stoughton, MA' 'San Ramon, CA' 'Huntsville, AL' 'Ladera Heights, CA'
 'Orland Park, IL' 'Artesia, CA' 'Olds, Canada' 'Munich, Germany'
 'Bloomington, IN' 'Auburn, CA' 'Lake Hughes, CA' 'Islandia, NY'
 'Paradise Valley, AZ' 'Columbia, SC' 'Los Gatos, CA'
 'Massachusetts, United States' 'Suisun City, CA' 'Fall River, MA'
 'Baltimore, MD' 'Holland, MI' 'Chino Hills, CA' 'Sausalito, CA'
 'Aspen, CO' 'Fremont, CA' 'Kathmandu, Nepal' 'Columbus, OH'
 'Florida, United States' 'Bay Islands Department, Honduras'
 'Connecticut, United States' 'Buena Park, CA' 'Trieste, Italy'
 'Provo, UT' 'MÃ¡laga, Spain' 'South Portland, ME' 'Alexandria, VA'
 'Lennox, CA' 'Pearland, TX' 'Reno, NV' 'Rolling Hills, CA'
 'Irwindale, CA' 'Australia' 'Mumbai, India' 'Bear Valley Springs, CA'
 'Nacogdoches, TX' 'Rohnert Park, CA' 'Idaho, United States'
 'Fajardo, Puerto Rico' 'Jacksonville, FL' 'Jonesboro, GA'
 'Vitoria-Gasteiz, Spain' 'Peoria, AZ' 'Arlington Heights, IL'
 'Brighton, Australia' 'Palm Beach, Australia' 'Albany, CA'
 'Clarksburg, MO' 'Gothenburg, Sweden' 'La Habra Heights, CA'
 'West Haven, UT' 'QuÃ©bec, Canada' 'Cypress, CA' 'Sandia Park, NM'
 'Clearwater, FL' 'Morristown, TN' 'Placerville, CA' 'Universal City, CA'
 'Warsaw, Poland' 'Merritt Island, FL' 'Costa Mesa, CA' 'Sheridan, WY'
 'Woodland, CA' 'Sarasota, FL' 'Palm Beach, FL' 'Indianapolis, IN'
 'Fallbrook, CA' 'Hillsdale, NY' 'St. Louis, MO' 'Saint Paul, MN'
 'New Rochelle, NY' 'Santo Domingo, Dominican Republic' 'Kailua, HI'
 'Clarksville, TN' 'Christchurch, New Zealand' 'East Hampton, NY'
 'Aledo, TX' 'Wailea-Makena, HI' 'La Mirada, CA' 'Salt Lake City, UT'
 'Douglasville, GA' 'Jamaica' 'Norfolk, VA' 'Colfax, CA'
 'Prachuap Khiri Khan, Thailand' 'Lacey, WA' 'Albuquerque, NM'
 'Bell Gardens, CA' 'Charlottesville, VA' 'Nambe, NM' 'Kiev, Ukraine'
 'Savannah, GA' 'Montgomery, OH' 'North Las Vegas, NV'
 'Arizona, United States' 'Burlingame, CA' 'San Marino, CA' 'Upland, CA'
 'Redwood City, CA' 'Meito Ward, Japan' 'Winston-Salem, NC'
 'Wofford Heights, CA' 'Maurepas, France' 'Oakhurst, CA' 'Haleiwa, HI'
 'Acireale, Italy' 'Wilmington, DE' 'East Whittier, CA' 'Richmond, VA'
 'Montana, United States' 'Red Hook, NY' 'Pomona, NY' 'Clovis, CA'
 'Dakar, Senegal' 'Renton, WA' 'Montpellier, France' 'Tualatin, OR'
 'Morocco, IN' 'Playa del Carmen, Mexico' 'Henrico, VA'
 'La Libertad, El Salvador' 'East Lansdowne, PA' 'Laguna Niguel, CA'
 'Pascagoula, MS' 'Accra, Ghana' 'Bushnell, FL' 'Cordova Bay, Canada'
 'Willow Creek, CA' 'Benbrook, TX' 'Sugarloaf, CA' 'Milwaukee, WI'
 'Emeryville, CA' 'Fall Creek, OR' 'Evanston, IL' 'Stone Mountain, GA'
 'La Palma, CA' 'Industry, CA' 'Westminster, CA' 'Tehachapi, CA'
 'Hayward, CA' 'Mount Prospect, IL' 'Weehawken, NJ' 'Berea, OH'
 'Golden Shores, AZ' 'Alpine, NJ' 'Seoul, South Korea' 'Newport News, VA'
 'Earth City, MO' 'Hollywood Hills, SC' 'Prescott Valley, AZ' 'Dallas, GA'
 'Alaska, MI' 'Davis, CA' 'Ciales, Puerto Rico' 'Seward, AK'
 'Nosara, Costa Rica' 'South El Monte, CA' 'Tallahassee, FL'
 'South San Francisco, CA' 'Granite Bay, CA' 'Frisco, TX'
 'Mission Hills, CA' 'Arvada, CO' 'La Quinta, CA' 'Bothell, WA'
 'Finleyville, PA' 'Spring Valley, NV' 'Richmond, CA' 'Miranda, CA'
 'West Tisbury, MA' 'Macon, GA' 'Belvedere, CA'
 'Buckingham, United Kingdom' 'Bangkok, Thailand' 'Traverse City, MI'
 'Cincinnati, OH' 'Oak Hills, CA' 'East San Gabriel, CA' 'Montclair, CA'
 'Durango, CO' 'Powell, WY' 'Harriman, NY' 'Spring, TX' 'Solana Beach, CA'

In [67]:
variables = [
    'review_scores_rating',
    'host_response_time',
    'host_response_rate',
    'host_acceptance_rate',
    'host_identity_verified',
    'host_listings_count',
    'room_type',
    'accommodates',
    'bedrooms',
    'bathrooms',
    'bathrooms_text',
    'price',
    'instant_bookable',
    'minimum_nights',
    'maximum_nights',
    'number_of_reviews_ltm'
]

df[variables]

,review_scores_rating,host_response_time,host_response_rate,host_acceptance_rate,host_identity_verified,host_listings_count,room_type,accommodates,bedrooms,bathrooms,bathrooms_text,price,instant_bookable,minimum_nights,maximum_nights,number_of_reviews_ltm
0,4.84,within an hour,100%,69%,t,1.0,Private room,2,1.0,1.0,1 shared bath,$65.00,f,2,28,7
1,4.83,within an hour,100%,99%,t,4.0,Entire home/apt,3,0.0,1.0,1 bath,$109.00,f,2,14,60
2,4.82,within an hour,100%,82%,t,3.0,Entire home/apt,2,1.0,1.0,1 bath,$106.00,f,30,175,2
3,4.90,within a day,100%,NaN,t,1.0,Entire home/apt,2,1.0,NaN,NaN,$110.00,f,30,730,0
4,4.95,within a few hours,100%,63%,t,1.0,Entire home/apt,1,1.0,1.0,1 bath,$109.00,f,30,60,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45026,NaN,within an hour,100%,99%,t,9.0,Entire home/apt,3,1.0,1.0,1 bath,$403.00,t,1,29,0
45027,NaN,within a few hours,100%,92%,t,3.0,Entire home/apt,6,3.0,3.5,3.5 baths,$417.00,t,30,365,0
45028,NaN,within an hour,100%,100%,t,51.0,Entire home/apt,8,3.0,3.0,3 baths,$400.00,t,30,365,0
45029,NaN,within an hour,85%,49%,t,4.0,Entire home/apt,2,1.0,1.0,1 bath,$64.00,f,1,365,0
45030,NaN,within an hour,100%,100%,t,18.0,Entire home/apt,5,1.0,2.0,2 baths,$199.00,t,2,365,0

In [68]:
df[variables].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45031 entries, 0 to 45030
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   review_scores_rating    32383 non-null  float64
 1   host_response_time      34627 non-null  object
 2   host_response_rate      34627 non-null  object
 3   host_acceptance_rate    35297 non-null  object
 4   host_identity_verified  44958 non-null  object
 5   host_listings_count     44958 non-null  float64
 6   room_type               45031 non-null  object
 7   accommodates            45031 non-null  int64
 8   bedrooms                42037 non-null  float64
 9   bathrooms               35923 non-null  float64
 10  bathrooms_text          45003 non-null  object
 11  price                   35867 non-null  object
 12  instant_bookable        45031 non-null  object
 13  minimum_nights          45031 non-null  int64
 14  maximum_nights          45031 non-null  int64
 15  number_of_reviews_ltm   45031 non-null  int64
dtypes: float64(4), int64(4), object(8)
memory usage: 5.5+ MB

In [69]:
df[df["bathrooms"].isnull() & df["bathrooms_text"].isnull()]

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
3,79832,https://www.airbnb.com/rooms/79832,20250301213405,2025-03-02,city scrape,Guest Quarters @ the Hollywood Sign,Guest House,NaN,https://a0.muscache.com/pictures/541078/35c6dc...,28569,...,4.95,4.93,4.91,HSR19-002716,f,1,1,0,0,2.84
10,241906,https://www.airbnb.com/rooms/241906,20250301213405,2025-03-03,previous scrape,"One Private Room in Studio City, CA",NaN,NaN,https://a0.muscache.com/pictures/2274779/a2690...,1242157,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
185,552216,https://www.airbnb.com/rooms/552216,20250301213405,2025-03-03,city scrape,Artist space / cream room / garden,After many years we are re-opening our doors t...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,8585179,...,4.96,4.91,4.96,NaN,f,1,0,1,0,0.16
320,688583,https://www.airbnb.com/rooms/688583,20250301213405,2025-03-03,city scrape,Stylish Suite in Silver Lake,NaN,NaN,https://a0.muscache.com/pictures/9166812/3cb64...,3515462,...,4.97,4.95,4.92,HSR23-003493,f,1,1,0,0,1.25
440,1053404,https://www.airbnb.com/rooms/1053404,20250301213405,2025-03-03,previous scrape,Bedroom with antique brass bed,NaN,NaN,https://a0.muscache.com/pictures/15843851/5cd0...,5799839,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
6171,19801464,https://www.airbnb.com/rooms/19801464,20250301213405,2025-03-03,previous scrape,Malibu Spa Suite w/ special features; local ac...,Master bedroom/bath/screening room with unique...,Secluded from neighbors and street with a priv...,https://a0.muscache.com/pictures/56ee7804-99e3...,131471979,...,NaN,NaN,NaN,NaN,f,3,0,3,0,NaN
9169,28702023,https://www.airbnb.com/rooms/28702023,20250301213405,2025-03-03,previous scrape,*BEST LOCATION IN LA* Your own Bedroom & Bathroom,"*PLZ READ ALL INFO BEFORE BOOKING, INCLUDING H...","West Hollywood is in the heart of Los Angeles,...",https://a0.muscache.com/pictures/hosting/Hosti...,11507720,...,4.93,4.98,4.77,NaN,f,1,0,1,0,0.72
12692,40117496,https://www.airbnb.com/rooms/40117496,20250301213405,2025-03-03,previous scrape,Room with view and private bathroom near UCLA,NaN,NaN,https://a0.muscache.com/pictures/5f0a0ee2-19d0...,10055368,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
15857,48904220,https://www.airbnb.com/rooms/48904220,20250301213405,2025-03-03,previous scrape,Casita at Cactus Rose Gardens,Glamp out in our tiny off grid cabin. No plumb...,NaN,https://a0.muscache.com/pictures/f3614da8-6d62...,7760022,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
16200,49599757,https://www.airbnb.com/rooms/49599757,20250301213405,2025-03-03,city scrape,It has a free WiFi,NaN,NaN,https://a0.muscache.com/pictures/c6375741-af17...,136203024,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
28965,973118182858485759,https://www.airbnb.com/rooms/973118182858485759,20250301213405,2025-03-03,city scrape,Cozy on the lake,Welcome to your luxurious place in the heart o...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,431052375,...,NaN,NaN,NaN,NaN,f,10,9,1,0,NaN
29853,1003695221674218624,https://www.airbnb.com/rooms/1003695221674218624,20250301213405,2025-03-02,city scrape,Large Furnished Room,Weâ€™re looking for a short term or long term ro...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,16839676,...,NaN,NaN,NaN,Exempt - This listing is a transient occupancy...,t,1,0,1,0,NaN
30289,1019634397769402037,https://www.airbnb.com/rooms/1019634397769402037,20250301213405,2025-03-03,city scrape,Quiet Room,NaN,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,545432207,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
33039,1112544491324534323,https://www.airbnb.com/rooms/1112544491324534323,20250301213405,2025-03-02,city scrape,Florence Private Bedroom 9 XO + Parking,> Private room with shared bathroom CoLiving h...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,14936368,...,5.00,5.00,5.00,NaN,f,75,8,67,0,0.73
33380,1119801506391799751,https://www.airbnb.com/rooms/1119801506391799751,20250301213405,2025-03-02,city scrape,Luxurious Queen Room,Welcome to your spacious and comfortable retre...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,253360984,...,4.67,4.44,4.44,NaN,f,1,0,1,0,0.83
33509,1126259081024929753,https://www.airbnb.com/rooms/1126259081024929753,20250301213405,2025-03-03,city scrape,Helen's place,Reconnect with loved ones in this family-f<br ...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,570273607,...,NaN,NaN,NaN,NaN,t,2,0,2,0,NaN
35797,1184359343559529012,https://www.airbnb.com/rooms/1184359343559529012,20250301213405,2025-03-02,city scrape,Private bedroom for rent. Shared bath/kitchen.,Keep it simple at this peaceful and centrally-...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,584944884,...,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
37329,1223199630618706997,https://www.airbnb.com/rooms/1223199630618706997,20250301213405,2025-03-02,city scrape,Beach Apartment,Welcome to your cozy retreat in the heart of L...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,72826461,...,4.00,5.00,5.00,Exempt,f,2,1,1,0,0.33
37439,1228457943000509840,https://www.airbnb.com/rooms/1228457943000509840,20250301213405,2025-03-03,city scrape,Mansion on top of the hill - entire master suite,"A perfect place to stay for recreation, inspir...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,432933117,...,5.00,5.00,4.78,NaN,f,1,1,0,0,1.48
37895,1239107567681424651,https://www.airbnb.com/rooms/1239107567681424651,20250301213405,2025-03-02,city scrape,â€œStylish 1BR apt w/ pool,Discover this stylish 1-bdrm apt in the heart ...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,72826461,...,3.83,4.67,4.33,Exempt,f,2,1,1,0,1.22
42308,1328306109633064890,https://www.airbnb.com/rooms/1328306109633064890,20250301213405,2025-03-03,city scrape,Stylish Room+Bath in Homeâ€“Quiet & Private,Private room with attached private bathroom. I...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,74371417,...,NaN,NaN,NaN,NaN,f,4,1,3,0,NaN
44565,1359567054410679132,https://www.airbnb.com/rooms/1359567054410679132,20250301213405,2025-03-02,city scrape,Best location. bedroom with attached bath and ...,Relaxing. peaceful. privacy. pool. outdoor sea...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,48102874,...,NaN,NaN,NaN,HSR24-003150,t,2,1,1,0,NaN

In [70]:
df[df["bathrooms"].notnull() & df["bathrooms_text"].isnull()][variables]

,review_scores_rating,host_response_time,host_response_rate,host_acceptance_rate,host_identity_verified,host_listings_count,room_type,accommodates,bedrooms,bathrooms,bathrooms_text,price,instant_bookable,minimum_nights,maximum_nights,number_of_reviews_ltm
6236,4.8,within a day,75%,100%,t,21.0,Hotel room,4,2.0,1.5,NaN,$823.00,f,1,365,2
7988,NaN,within an hour,100%,100%,t,3.0,Hotel room,4,1.0,1.5,NaN,NaN,t,1,28,0
14535,NaN,NaN,NaN,NaN,t,1.0,Private room,1,1.0,0.0,NaN,$142.00,t,30,30,0
15318,NaN,NaN,NaN,NaN,t,2.0,Private room,2,1.0,0.0,NaN,$240.00,t,1,1125,0
16193,NaN,NaN,NaN,NaN,t,2.0,Private room,1,1.0,0.0,NaN,$50.00,t,30,1125,0
18209,NaN,within a few hours,67%,NaN,t,2.0,Private room,2,1.0,0.0,NaN,$37.00,f,1,365,0

In [71]:
# Turn score rating into binary classifier (>=4.5, <4.5)
# Host_response_time into dummy variables
# Host_response_rate and host_acceptance_rate turned into decimals - remove %, /100
# room_type to dummy variables
# For cleaning the bathrooms, if bathrooms is null, extract number from bathrooms_text, else use bathrooms?
# Cleaning price - remove $

In [72]:
df.duplicated().sum()

0

In [73]:
df_variables = df[variables].copy()

# --- Clean host_response_rate and host_acceptance_rate: remove '%' and divide by 100 ---
def percent_to_float(x):
    if isinstance(x, str) and x.endswith('%'):
        return float(x.strip('%')) / 100
    return np.nan

df_variables["host_response_rate"] = df_variables["host_response_rate"].apply(percent_to_float)
df_variables["host_acceptance_rate"] = df_variables["host_acceptance_rate"].apply(percent_to_float)
df_variables

,review_scores_rating,host_response_time,host_response_rate,host_acceptance_rate,host_identity_verified,host_listings_count,room_type,accommodates,bedrooms,bathrooms,bathrooms_text,price,instant_bookable,minimum_nights,maximum_nights,number_of_reviews_ltm
0,4.84,within an hour,1.00,0.69,t,1.0,Private room,2,1.0,1.0,1 shared bath,$65.00,f,2,28,7
1,4.83,within an hour,1.00,0.99,t,4.0,Entire home/apt,3,0.0,1.0,1 bath,$109.00,f,2,14,60
2,4.82,within an hour,1.00,0.82,t,3.0,Entire home/apt,2,1.0,1.0,1 bath,$106.00,f,30,175,2
3,4.90,within a day,1.00,NaN,t,1.0,Entire home/apt,2,1.0,NaN,NaN,$110.00,f,30,730,0
4,4.95,within a few hours,1.00,0.63,t,1.0,Entire home/apt,1,1.0,1.0,1 bath,$109.00,f,30,60,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45026,NaN,within an hour,1.00,0.99,t,9.0,Entire home/apt,3,1.0,1.0,1 bath,$403.00,t,1,29,0
45027,NaN,within a few hours,1.00,0.92,t,3.0,Entire home/apt,6,3.0,3.5,3.5 baths,$417.00,t,30,365,0
45028,NaN,within an hour,1.00,1.00,t,51.0,Entire home/apt,8,3.0,3.0,3 baths,$400.00,t,30,365,0
45029,NaN,within an hour,0.85,0.49,t,4.0,Entire home/apt,2,1.0,1.0,1 bath,$64.00,f,1,365,0
45030,NaN,within an hour,1.00,1.00,t,18.0,Entire home/apt,5,1.0,2.0,2 baths,$199.00,t,2,365,0

In [74]:
import re
# ---  Clean bathrooms: use 'bathrooms' if not null, else extract number from 'bathrooms_text' ---
def extract_bathroom_count(row):
    if pd.notnull(row["bathrooms"]):
        return row["bathrooms"]
    elif pd.notnull(row["bathrooms_text"]):
        match = re.search(r'(\d+\.?\d*)', row["bathrooms_text"])
        if match:
            return float(match.group(1))
    return np.nan

df_variables["clean_bathrooms"] = df_variables.apply(extract_bathroom_count, axis=1)
df_variables["clean_bathrooms"]

0        1.0
1        1.0
2        1.0
3        NaN
4        1.0
        ...
45026    1.0
45027    3.5
45028    3.0
45029    1.0
45030    2.0
Name: clean_bathrooms, Length: 45031, dtype: float64

In [75]:
# --- Clean price: remove "$" and commas, convert to float ---
def clean_price(val):
    if isinstance(val, str):
        return float(val.replace("$", "").replace(",", ""))
    return np.nan

df_variables["price"] = df_variables["price"].apply(clean_price)
df_variables["price"]

0         65.0
1        109.0
2        106.0
3        110.0
4        109.0
         ...
45026    403.0
45027    417.0
45028    400.0
45029     64.0
45030    199.0
Name: price, Length: 45031, dtype: float64

In [76]:
df_variables

,review_scores_rating,host_response_time,host_response_rate,host_acceptance_rate,host_identity_verified,host_listings_count,room_type,accommodates,bedrooms,bathrooms,bathrooms_text,price,instant_bookable,minimum_nights,maximum_nights,number_of_reviews_ltm,clean_bathrooms
0,4.84,within an hour,1.00,0.69,t,1.0,Private room,2,1.0,1.0,1 shared bath,65.0,f,2,28,7,1.0
1,4.83,within an hour,1.00,0.99,t,4.0,Entire home/apt,3,0.0,1.0,1 bath,109.0,f,2,14,60,1.0
2,4.82,within an hour,1.00,0.82,t,3.0,Entire home/apt,2,1.0,1.0,1 bath,106.0,f,30,175,2,1.0
3,4.90,within a day,1.00,NaN,t,1.0,Entire home/apt,2,1.0,NaN,NaN,110.0,f,30,730,0,NaN
4,4.95,within a few hours,1.00,0.63,t,1.0,Entire home/apt,1,1.0,1.0,1 bath,109.0,f,30,60,5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45026,NaN,within an hour,1.00,0.99,t,9.0,Entire home/apt,3,1.0,1.0,1 bath,403.0,t,1,29,0,1.0
45027,NaN,within a few hours,1.00,0.92,t,3.0,Entire home/apt,6,3.0,3.5,3.5 baths,417.0,t,30,365,0,3.5
45028,NaN,within an hour,1.00,1.00,t,51.0,Entire home/apt,8,3.0,3.0,3 baths,400.0,t,30,365,0,3.0
45029,NaN,within an hour,0.85,0.49,t,4.0,Entire home/apt,2,1.0,1.0,1 bath,64.0,f,1,365,0,1.0
45030,NaN,within an hour,1.00,1.00,t,18.0,Entire home/apt,5,1.0,2.0,2 baths,199.0,t,2,365,0,2.0

In [77]:
df_variables = df_variables.drop(['bathrooms', 'bathrooms_text'], axis=1)
df_variables

,review_scores_rating,host_response_time,host_response_rate,host_acceptance_rate,host_identity_verified,host_listings_count,room_type,accommodates,bedrooms,price,instant_bookable,minimum_nights,maximum_nights,number_of_reviews_ltm,clean_bathrooms
0,4.84,within an hour,1.00,0.69,t,1.0,Private room,2,1.0,65.0,f,2,28,7,1.0
1,4.83,within an hour,1.00,0.99,t,4.0,Entire home/apt,3,0.0,109.0,f,2,14,60,1.0
2,4.82,within an hour,1.00,0.82,t,3.0,Entire home/apt,2,1.0,106.0,f,30,175,2,1.0
3,4.90,within a day,1.00,NaN,t,1.0,Entire home/apt,2,1.0,110.0,f,30,730,0,NaN
4,4.95,within a few hours,1.00,0.63,t,1.0,Entire home/apt,1,1.0,109.0,f,30,60,5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45026,NaN,within an hour,1.00,0.99,t,9.0,Entire home/apt,3,1.0,403.0,t,1,29,0,1.0
45027,NaN,within a few hours,1.00,0.92,t,3.0,Entire home/apt,6,3.0,417.0,t,30,365,0,3.5
45028,NaN,within an hour,1.00,1.00,t,51.0,Entire home/apt,8,3.0,400.0,t,30,365,0,3.0
45029,NaN,within an hour,0.85,0.49,t,4.0,Entire home/apt,2,1.0,64.0,f,1,365,0,1.0
45030,NaN,within an hour,1.00,1.00,t,18.0,Entire home/apt,5,1.0,199.0,t,2,365,0,2.0

In [78]:
df_variables.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45031 entries, 0 to 45030
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   review_scores_rating    32383 non-null  float64
 1   host_response_time      34627 non-null  object
 2   host_response_rate      34627 non-null  float64
 3   host_acceptance_rate    35297 non-null  float64
 4   host_identity_verified  44958 non-null  object
 5   host_listings_count     44958 non-null  float64
 6   room_type               45031 non-null  object
 7   accommodates            45031 non-null  int64
 8   bedrooms                42037 non-null  float64
 9   price                   35867 non-null  float64
 10  instant_bookable        45031 non-null  object
 11  minimum_nights          45031 non-null  int64
 12  maximum_nights          45031 non-null  int64
 13  number_of_reviews_ltm   45031 non-null  int64
 14  clean_bathrooms         44986 non-null  float64
dtypes: float64(7), int64(4), object(4)
memory usage: 5.2+ MB

In [79]:
df_variables["price"].isnull().mean()

0.20350425262596877

In [80]:
df_variables["review_scores_rating"].isnull().mean()

0.2808731762563567

In [81]:
# Drop rows where the rating is missing
df_variables = df_variables[df_variables["review_scores_rating"].notnull()].copy()

# Create the binary target column
df_variables["high_rating"] = (df_variables["review_scores_rating"] >= 4.5).astype(int)

df_variables = df_variables.drop('review_scores_rating', axis=1)
df_variables

,host_response_time,host_response_rate,host_acceptance_rate,host_identity_verified,host_listings_count,room_type,accommodates,bedrooms,price,instant_bookable,minimum_nights,maximum_nights,number_of_reviews_ltm,clean_bathrooms,high_rating
0,within an hour,1.0,0.69,t,1.0,Private room,2,1.0,65.0,f,2,28,7,1.0,1
1,within an hour,1.0,0.99,t,4.0,Entire home/apt,3,0.0,109.0,f,2,14,60,1.0,1
2,within an hour,1.0,0.82,t,3.0,Entire home/apt,2,1.0,106.0,f,30,175,2,1.0,1
3,within a day,1.0,NaN,t,1.0,Entire home/apt,2,1.0,110.0,f,30,730,0,NaN,1
4,within a few hours,1.0,0.63,t,1.0,Entire home/apt,1,1.0,109.0,f,30,60,5,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44777,within an hour,1.0,0.67,t,1.0,Private room,2,1.0,107.0,f,1,365,1,1.0,1
44807,within an hour,1.0,1.00,t,4.0,Private room,2,1.0,62.0,f,1,365,2,0.5,1
44845,within an hour,1.0,0.89,t,4.0,Entire home/apt,2,1.0,59.0,f,1,365,1,1.0,1
44899,within an hour,1.0,1.00,t,1.0,Private room,2,1.0,104.0,f,1,365,1,1.0,1
44947,within an hour,1.0,1.00,t,3.0,Entire home/apt,2,1.0,78.0,t,1,365,1,1.0,1

In [82]:
df_variables["high_rating"].value_counts(normalize=True)

high_rating
1    0.907174
0    0.092826
Name: proportion, dtype: float64

In [83]:
df_variables.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32383 entries, 0 to 44947
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   host_response_time      26482 non-null  object
 1   host_response_rate      26482 non-null  float64
 2   host_acceptance_rate    27412 non-null  float64
 3   host_identity_verified  32346 non-null  object
 4   host_listings_count     32346 non-null  float64
 5   room_type               32383 non-null  object
 6   accommodates            32383 non-null  int64
 7   bedrooms                30432 non-null  float64
 8   price                   26374 non-null  float64
 9   instant_bookable        32383 non-null  object
 10  minimum_nights          32383 non-null  int64
 11  maximum_nights          32383 non-null  int64
 12  number_of_reviews_ltm   32383 non-null  int64
 13  clean_bathrooms         32362 non-null  float64
 14  high_rating             32383 non-null  int32
dtypes: float64(6), int32(1), int64(4), object(4)
memory usage: 3.8+ MB

In [84]:
# Group by high_rating and calculate % missing for a given column
def missing_by_rating(df, column):
    return (
        df[column].isnull()
        .groupby(df["high_rating"])
        .mean()
        .rename("percent_missing")
        .mul(100)
        .round(2)
    )

# Example for host_response_rate
missing_by_rating(df_variables, "host_response_rate")

high_rating
0    21.86
1    17.85
Name: percent_missing, dtype: float64

In [85]:
# Get all numeric columns (excluding the target column itself if needed)
numeric_cols = df_variables.select_dtypes(include=["number"]).columns.drop("high_rating", errors="ignore")

# Store results in a dictionary
missing_by_group = {}

# Loop through numeric columns
for col in numeric_cols:
    missing_rates = (
        df_variables[col].isnull()
        .groupby(df_variables["high_rating"])
        .mean()
        .mul(100)
        .round(2)
    )
    missing_by_group[col] = missing_rates

# Convert to DataFrame for easy viewing
missing_by_group_df = pd.DataFrame(missing_by_group).T
missing_by_group_df.columns = ["% missing (low rating)", "% missing (high rating)"]

missing_by_group_df["diff"] = (
    missing_by_group_df["% missing (low rating)"] - missing_by_group_df["% missing (high rating)"]
)
missing_by_group_df.sort_values("diff", ascending=False)

                       % missing (low rating)  % missing (high rating)  diff
price                                   23.55                    18.04  5.51
host_acceptance_rate                    19.43                    14.93  4.50
host_response_rate                      21.86                    17.85  4.01
bedrooms                                 7.42                     5.88  1.54
clean_bathrooms                          0.13                     0.06  0.07
host_listings_count                      0.13                     0.11  0.02
accommodates                             0.00                     0.00  0.00
minimum_nights                           0.00                     0.00  0.00
maximum_nights                           0.00                     0.00  0.00
number_of_reviews_ltm                    0.00                     0.00  0.00

In [86]:
# Create an indicator flag for missingness (since it seems to be related to high and low rating)
for col in ["price", "host_acceptance_rate", "host_response_rate"]:
    df_variables[f"{col}_missing"] = df_variables[col].isnull().astype(int)
# Impute the missing values with the median for these columns so we don't have missing values
for col in ["price", "host_acceptance_rate", "host_response_rate"]:
    median_val = df_variables[col].median()
    df_variables[col] = df_variables[col].fillna(median_val)

df_variables.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32383 entries, 0 to 44947
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   host_response_time            26482 non-null  object
 1   host_response_rate            32383 non-null  float64
 2   host_acceptance_rate          32383 non-null  float64
 3   host_identity_verified        32346 non-null  object
 4   host_listings_count           32346 non-null  float64
 5   room_type                     32383 non-null  object
 6   accommodates                  32383 non-null  int64
 7   bedrooms                      30432 non-null  float64
 8   price                         32383 non-null  float64
 9   instant_bookable              32383 non-null  object
 10  minimum_nights                32383 non-null  int64
 11  maximum_nights                32383 non-null  int64
 12  number_of_reviews_ltm         32383 non-null  int64
 13  clean_bathrooms               32362 non-null  float64
 14  high_rating                   32383 non-null  int32
 15  price_missing                 32383 non-null  int32
 16  host_acceptance_rate_missing  32383 non-null  int32
 17  host_response_rate_missing    32383 non-null  int32
dtypes: float64(6), int32(4), int64(4), object(4)
memory usage: 4.2+ MB

In [87]:
# Impute bedrooms with median
df_variables["bedrooms"] = df_variables["bedrooms"].fillna(df_variables["bedrooms"].median())

# Impute clean_bathrooms with median
df_variables["clean_bathrooms"] = df_variables["clean_bathrooms"].fillna(df_variables["clean_bathrooms"].median())

# Impute host_listings_count with median
df_variables["host_listings_count"] = df_variables["host_listings_count"].fillna(df_variables["host_listings_count"].median())

In [88]:
# Convert host_identity_verified to binary
df_variables["host_identity_verified"] = df_variables["host_identity_verified"].map({"t": 1, "f": 0})
df_variables["host_identity_verified"] = df_variables["host_identity_verified"].fillna(0)

# One-hot encode host_response_time, room_type, and instant_bookable
df_variables = pd.get_dummies(
    df_variables,
    columns=["host_response_time", "room_type", "instant_bookable"],
    prefix=["response_time", "room", "bookable"],
    drop_first=True,
    dummy_na=True
)
print(df_variables.isnull().sum().sort_values(ascending=False).head())

host_response_rate              0
host_acceptance_rate_missing    0
bookable_t                      0
room_nan                        0
room_Shared room                0
dtype: int64

In [91]:
df_variables.info()
df_variables.head()

<class 'pandas.core.frame.DataFrame'>
Index: 32383 entries, 0 to 44947
Data columns (total 25 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   host_response_rate                32383 non-null  float64
 1   host_acceptance_rate              32383 non-null  float64
 2   host_identity_verified            32383 non-null  float64
 3   host_listings_count               32383 non-null  float64
 4   accommodates                      32383 non-null  int64
 5   bedrooms                          32383 non-null  float64
 6   price                             32383 non-null  float64
 7   minimum_nights                    32383 non-null  int64
 8   maximum_nights                    32383 non-null  int64
 9   number_of_reviews_ltm             32383 non-null  int64
 10  clean_bathrooms                   32383 non-null  float64
 11  high_rating                       32383 non-null  int32
 12  price_missing                     32383 non-null  int32
 13  host_acceptance_rate_missing      32383 non-null  int32
 14  host_response_rate_missing        32383 non-null  int32
 15  response_time_within a day        32383 non-null  bool
 16  response_time_within a few hours  32383 non-null  bool
 17  response_time_within an hour      32383 non-null  bool
 18  response_time_nan                 32383 non-null  bool
 19  room_Hotel room                   32383 non-null  bool
 20  room_Private room                 32383 non-null  bool
 21  room_Shared room                  32383 non-null  bool
 22  room_nan                          32383 non-null  bool
 23  bookable_t                        32383 non-null  bool
 24  bookable_nan                      32383 non-null  bool
dtypes: bool(10), float64(7), int32(4), int64(4)
memory usage: 3.8 MB

,host_response_rate,host_acceptance_rate,host_identity_verified,host_listings_count,accommodates,bedrooms,price,minimum_nights,maximum_nights,number_of_reviews_ltm,...,response_time_within a day,response_time_within a few hours,response_time_within an hour,response_time_nan,room_Hotel room,room_Private room,room_Shared room,room_nan,bookable_t,bookable_nan
0,1.0,0.69,1.0,1.0,2,1.0,65.0,2,28,7,...,False,False,True,False,False,True,False,False,False,False
1,1.0,0.99,1.0,4.0,3,0.0,109.0,2,14,60,...,False,False,True,False,False,False,False,False,False,False
2,1.0,0.82,1.0,3.0,2,1.0,106.0,30,175,2,...,False,False,True,False,False,False,False,False,False,False
3,1.0,0.98,1.0,1.0,2,1.0,110.0,30,730,0,...,True,False,False,False,False,False,False,False,False,False
4,1.0,0.63,1.0,1.0,1,1.0,109.0,30,60,5,...,False,True,False,False,False,False,False,False,False,False